server:
  port: 80
  max-http-header-size: 10240

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1
#  mail:
#    #邮件协议smtp
#    host: smtp.qq.com
#    #发送者的邮件的用户名
#    username: 1172544385@qq.com
#    #使用的编码
#    default-encoding: utf-8
#    #移动端客户授权码(在邮箱中设置)
#    password: hgwrjqamlmubjehj

mybatis-plus:
  mapper-locations: classpath*:cn/stylefeng/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

log:
  path: _app_logs

file:
  uploadFolder: D:/tmp/
  #uploadFolder: /home/JKY/data/

alipay:
  app_id: 2016102300743088
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgT6NlKz7PzE9QuiI1yita1L3vJXK+EjhLfHNHdcUtNnw3tvOmqs4FXtlDTEllpGUmPEQHngpp1B/EMEuWrHG8QpVEu6P/9Dtw8vPTwwJPSAKJv2S1i5+UxeDYLLY36qMREwaxw2meeWbOTYkSxwDGOsyFWHTCMWYh4E7iVDRuS3zW/mc5dMRwWDF9iY8QxVDcMn5qZo+8YYq+0AKy60tBFDCKRdXv5L8m77+EqHrqe4hO7Tw0oU9Dt+0k7LQux7hZNKaGUWojukz9xZKvmiblOZz0ltdzwjiYhsFTSR6y86On01kNwtX5SCd82zv+fXvsJS0+WR7bwqELkl1cZGXdAgMBAAECggEAXpB7vxryc1t+0gzqTzaRuoPSAnbhp5NR191ylw22oUQJpEfslD0fSHW5zYP7q9R8wkA8lQ258NFrZ6xhemEAul/Ac4oIZNyqD6eRAzJ+c0v0C1N2Uc0p9nV/e6VsW7GyPUku4r9110Cfz0RXflcbctOOf349aawAJi2N+t5XC1PUwlHI052YR/oq4lDdtguhy4E60zO5ceFoZnc6kfyF974IUlQYHEqel7F2n3aa89qS+yqugFHNPntbBiKpWffVRRm5JpdD1pxM6EWZ86VYkNlfUXZns/tVxvYJmf95bwz/LCE3B63p29YdR0JLirw9831AdR5/OYyhJNWGACbWgQKBgQDpnUcrI4U+FVxJqfiR6QKNlinOjeF9l94RBRhukUBZPusi2Fb1/6b7LoY8mm6pTp9Fn/N2KELN8V9xrYaO4b8aaKpILNvsF5ebw9MToNiOV7baBKCyWJsKd4Xy7JR+oFc+BcFpXkpjaaqHd6a6tpxji3JsTr3hbum+EnpYg2CePQKBgQCvrC4a9bQc5yEMnyelWSAkBSbBWpesplom/2PAHrvMdAuqJONovxg0zqWVh6Yyxu0pMnbipGHAube+OecNkfKXMTYFvraXJvk8MSFHf1W98Ha6anodHgvup7InKz1Oo3HL0q+tjVxmVqPjhBQw4gIAhTsCIj0Q8DIS4wL7X7AAIQKBgQC7fPtiFsbX1aLUh/IzgBMJeOuil2HSPzD87d721eIT/hgORhw8n+nuix82wiZwAOZ4pW9qc9Nxnvcfr8lfILQTyM5o0H/MEf8eBuJ/TUafrqvUe4RQviXoF5bMKKzgl2SNJWddXkxLTsGKqS+JiAcpKQAzBlsD8tTrM783DHFdbQKBgGyFO9IRuJsmOKdYZiBhx1YZDJDjStEvzn9Kwy86jR7HDTGlKgpaCjUM9wNBUe0KMBWEBCcMDwsEbzqHAHHEmAzILKwt3RPQ0qRZYUqOocP9GQsdnaQBHLPoSkiiEHRUyYZ092uJ6OubWBDDVcnAxCXYJ9Swm/KrvvMl44Cv4sShAoGAakDkzWRkOMaGXEcBX6TiPxDK5BmvXIxwJQSqMagnwWcLf6Qx4XtO0BhQn+0PfEKOgHrc+KMsLAUdVi5f4XLFHNHy3YEZXNzPrIoWvIV10ARiRA7OCSMusYY7tbaHX+jeS8SwXXEbOqqaYQOdR9vBfvjvWXQRNmvx4cqS2QYBp0A
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoIaH4qtsD2bIgNUc+VxYUiXPAc3/vhA7hS2oAqqzFYsZcXpKv6QZU2SLwEZeS0dJPCPndnqRMDoKr+6GgQ7g6cQTSbndYCm11RqDe0tLNYdW8bmJWRujaLyGiElBbmT/8v4HGsaUE6R1/OL8uLDAJZ/yOA8YfIQwL4dVSoeATYfA9BSVWGgZwVLsngRo8rVQGdCC34lWe5B4XjNXw1xtS52LRceJJhgMcWmwi3DPOaslVkq0YJObHxzj4DXCDqe14KoiV6KVvS+p2zXiccj5AiPNo6Q60EuOZKiK3h8qAoWQv7jJoTxk4w7MgBVZVkgN9MaqtcxamEOFeE5xZ/vm0wIDAQAB
  website: eb10fb2eba95.ngrok.io
