server:
  port: 80
  max-http-header-size: 10240

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1
#  mail:
#    #邮件协议smtp
#    host: smtp.qq.com
#    #发送者的邮件的用户名
#    username: 1172544385@qq.com
#    #使用的编码
#    default-encoding: utf-8
#    #移动端客户授权码(在邮箱中设置)
#    password: hgwrjqamlmubjehj

mybatis-plus:
  mapper-locations: classpath*:cn/stylefeng/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

log:
  path: _app_logs

file:
  uploadFolder: D:/tmp/
  #uploadFolder: /home/JKY/data/
